# Generated by Django 2.0.2 on 2018-02-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival_team', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('goals_against', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GamesCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('yellow', 'yellow'), ('red', 'red')], max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Player')),
            ],
        ),
        migrations.CreateModel(
            name='GamesGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Player')),
            ],
        ),
    ]
