# Generated by Django 2.0.2 on 2018-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_games_gamescards_gamesgoals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamescards',
            options={'verbose_name_plural': 'Games Cards'},
        ),
        migrations.AlterModelOptions(
            name='gamesgoals',
            options={'verbose_name_plural': 'Games Goals'},
        ),
        migrations.AddField(
            model_name='games',
            name='minute',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='gamescards',
            name='minute',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
