# Generated by Django 2.0.2 on 2018-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20180222_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescards',
            name='minute',
        ),
        migrations.AddField(
            model_name='gamesgoals',
            name='minute',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
