# Generated by Django 2.0.2 on 2018-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_auto_20180222_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesgoals',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
